### ISSUE TITLE
Getting NetBeans Logger to Log FINE, FINER, and FINEST Messages

### ISSUE THREAD

**Issue by SeanCarrick** [PekinSOFT-Systems/Northwind-RCP#6]
I have finally figured out how to write log messages to the `messages.log` file from the platform application. However, it will only log messages at `Level.INFO` or higher and all debugging messages are lost.

In trying to lower the logging level to `Level.FINE`, nothing seems to be working, as only `Level.INFO` or higher continue to be logged.

### What I Have Tried
According to the information found at [wiki.netbeans.org](http://wiki.netbeans.org/HowToPassCommandLineArgumentsToANetBeansPlatformApplicationWhenRunInsideTheIDE), I added the following line to my `project.properties` file: `run.args.extra=-J-Dorg.level=FINEST -J-Dcom.level=FINEST -J-Djavax.level=FINEST -J-Djava.level=FINEST`.

However, that, nor any of the other combinations, including these:

`-J-Dorg.netbeans.core.startup.NbInstaller.level=FINE `

and

`-J-Dorg.netbeans.level=FINEST`

worked. I also tried setting the logging level of the `Logger` itself in the code:

```java
        Logger.getLogger(className).setLevel(Level.FINE);
        log = Logger.getLogger(CoATopComponent.class.getName());
```

I have also tried setting the level of the `log` variable directly:

```java
        log.setLevel(Level.FINE);
```

However, after all of these various ploys, the log is still only logging at `Level.INFO` or higher.

Any thoughts on this?

**Comment by jkovalsky** [comment]
Yes, you got it right. That should be fine in my opinion. If there is a bug, we can add FINEST logging around potentially guilty code and in the worst case we can debug the code in NetBeans, can't we? :)

**Comment by SeanCarrick** [comment]
OK, then. I guess that we can log debugging messages, temporarily at least, as `Level.INFO`. I mean, will logging like this really hurt the overall performance of the application?

However, if add FINEST logging around potentially guilty code, we wouldn't see the records in messages.log, so I am not sure how logging those messages will help us.

**Comment by jkovalsky** [comment]
I don't think `Level.INFO` will have any impact on performance unless you plan to introduce some complex calculations so if you like it, keep it!

**Comment by SeanCarrick** [comment]
OK. Thank you for your thoughts on this. I am going to go ahead and close this issue. From here on, we can just log our debugging message at the `INFO` level, but lower-level or CPU-extensive messages (such as the complex calculations you mentioned) can be logged at any level lower than `INFO`, so that they won't actually be logged by the system.
